
jobs:
  include:

    - stage: SimpleTest
      if: branch = master
      language: generic
      env: desc="Simple test"
      install:

        # install version of fastlane from Gemfile.lock
        - gem install bundler:2.0.2
        - (cd example; bundle install)
      script:
        echo Hello
